project:
  type: website

website:
  title: "Noel Mangai"
  favicon: "Headcrop2.jpg"
  
  page-footer:
    center: |
      [Contact Noel Mangai](mailto:Noelmangai001@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    background: "grey"
  search: 
    location: navbar
    type: overlay
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/noel-mangai/
format:
  html:
    theme:
      light: Flatly
      dark: darkly
    css: styles.css
    code-link: true
    code-fold: show
    code-tools: true
    highlight-style: github

editor: visual

